#!/bin/sh
 
OSNAME=`uname`
HARDWARENAME=`uname -m`
PLAT=$OSNAME.$HARDWARENAME

case $PLAT in
	Linux.ppc)
        echo "Configuring for the "$OSNAME" "$HARDWARENAME" platform"
		CPLUS=gcc
		CCOMP=gcc
		LINKER='gcc'
 		MAKE=make
 		
		COMPILER_FLAGS= "-D__linuxppc__ -Wno-multichar -pipe"
		INCLUDE_FLAG="-include"
		
		CORE_LINK_LIBS="-lpthread -ldl -lm -lcrypt"

		SHARED=-shared
		MODULE_LIBS=
		;;		

	Linux.i586 | \
	Linux.i686 | \
	Linux.x86_64)

        echo "Configuring for the "$OSNAME" "$HARDWARENAME" platform"
                CPLUS=gcc
                CCOMP=gcc
                LINKER='gcc'
                MAKE=make

                if [ "$PLAT" = "Linux.x86_64" ]; then
                        COMPILER_FLAGS="-D_REENTRANT -D__USE_POSIX -D__linux__ -pipe -fPIC"
                else
                        COMPILER_FLAGS="-D_REENTRANT -D__USE_POSIX -D__linux__ -pipe"
                fi

	        INCLUDE_FLAG="-include"
                CORE_LINK_LIBS="-lpthread -ldl -lstdc++ -lm -lcrypt"

                SHARED=-shared
                MODULE_LIBS=
                ;;

	Linux.mips)
        echo "Configuring for the "$OSNAME" "$HARDWARENAME" platform"
		CPLUS=gcc
		CCOMP=gcc
		LINKER='egcs'
 		MAKE=make
 		
		COMPILER_FLAGS="-D_REENTRANT -D__linux__ -Wno-multichar -pipe"
		INCLUDE_FLAG="-include"
		
		CORE_LINK_LIBS="-lpthread -ldl -lm -lcrypt"

		SHARED=-shared
		MODULE_LIBS=
		;;

	FreeBSD.i386)
        echo "Configuring for the "$OSNAME" "$HARDWARENAME" platform"
		CPLUS=gcc
		CCOMP=gcc
		LINKER="gcc"
 		MAKE=make
 		
		COMPILER_FLAGS=
		INCLUDE_FLAG="-include"
		
		CORE_LINK_LIBS="-pthread -lm -lcrypt"

		SHARED=-shared
		MODULE_LIBS="-lgcc -lstdc++"
		;;
	
	*)
		echo "I don't know your platform. I'll assume this is a Linux x86 platform."
		echo "Please edit this build script to add your platform."
		CPLUS=gcc
		CCOMP=gcc
		LINKER='egcs'
 		MAKE=make
 		
		COMPILER_FLAGS=-D__linux__
		INCLUDE_FLAG="-include"

		CORE_LINK_LIBS="-lpthread -ldl -lm -lcrypt"

		SHARED=-shared
		MODULE_LIBS=
		;;
esac

echo Building for $PLAT with $CPLUS
export CPLUS
export CCOMP
export LINKER
export COMPILER_FLAGS
export INCLUDE_FLAG
export CORE_LINK_LIBS
export SHARED
export MODULE_LIBS
echo Building My Auth Module for $PLAT with $CPLUS
$MAKE -f Makefile.POSIX $*
